### ISSUE TITLE
bug: With Capacitor 3.0 CAPPlugin's 'webView' and 'bridge' is now optional, why?

### ISSUE THREAD

**Issue by MortenGregersen** [ionic-team/capacitor-site#244]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli: 3.0.0-rc.0
  @capacitor/core: 3.0.0-rc.0
  @capacitor/android: 3.0.0-rc.0
  @capacitor/ios: 3.0.0-rc.0
```

### Platform(s)
iOS (Swift)

### Current Behavior

After upgrade to Capacitor 3.0 the following lines won't compile because `webView` and `bridge` on `CAPPlugin` is now seen as optional.
```
let configuration = self.webView.configuration <- The webView now has to be force unwrapped
self.bridge.triggerDocumentJSEvent(eventName: "bob")  <- The bridge now has to be force unwrapped
```

### Expected Behavior

This is fine if the `webView` and `bridge` are optional, but I can't find any information about this, and why this is changed. It is not clear if they are optional as they are defined in Objective-C without any nullability information provided.

So, are they optional or not? It would be useful with some nullability information added to the header.

### Other Technical Details

`npm --version` output: 6.14.9

`node --version` output: v12.14.0

`pod --version` output (iOS issues only): 1.10.1

**Comment by ikeith** [comment]
Yes, that change was overlooked for documentation and the site will be updated to match. `webView` is optional for the same reason `bridge` is, we needed to break the strong reference cycles between objects to address memory leaks.

This change in nullability [is documented in the header](https://github.com/ionic-team/capacitor/blob/5bc82f62974159ed3accfdbdb49e2dfbaf652152/ios/Capacitor/Capacitor/CAPPlugin.h#L9) otherwise Swift would not import it as a `weak` reference. The whole `CAPPlugin.h` header has been updated for 3.0 to explicitly annotate the relationships and arguments instead of the implicit `NS_ASSUME_NONNULL` it had before.

Also, I would encourage you not to force unwrap optionals; that is considered an anti-pattern in Swift. Using `guard` or `if let` statements or the `??` nil-coalescing operator are all much safer approaches.

**Comment by MortenGregersen** [comment]
Fine 👍🏻 I didn't see the `nullable` and `weak` in my header yesterday, I see it now. Everything is fine then.

We should of course strive to use conditional unwrapping of optionals, but in this upgrade I wanted to change as little code as possible, and if the optional properties will always be non-optional in reality right now, it was easier to force unwrap them.
