### ISSUE TITLE
Can't make sense of the background task example

### ISSUE THREAD

**Issue by coffeymatt** [ionic-team/capacitor-site#87]
With the background task documentation:

https://github.com/ionic-team/capacitor-site/blob/master/docs/reference/apis/background-task/index.md

"
 // In this function We might finish an upload, let a network request
// finish, persist some data, or perform some other task
"

How? In that example, the function is only executed when the app's state changes and the task is executed on the 'beforeExit' event. So how would you get a handle on let's say an observable http request in angular, and ensure execution continues until that's complete? Now matter how I seem to write it, it either doesn't run or the app doesn't continue in the background. (I'm trying to finish a http synchronisation operation in the background). I'm trying it on ios.

Would it be possible to incorporate an angular example with a http request that's been executed by a button that needs to complete?

**Comment by apolaina-ineat** [comment]
Any news on this? Any new examples?

**Comment by jcesarmobile** [comment]
I'm closing because the background task plugin was removed in Capacitor 3.

On Android the plugin wasn't doing anything as it was not needed, Android apps could keep running js code in background when the plugin was created. That might have changed in newer Android versions or newer WebView versions.

On iOS, even with the plugin, most javascript execution was halted as soon as the app enters the background, that's why `setTimeout` and `setInterval` are documented as not working, but there are more things that don't work. Some code might continue to run but will provide no "feedback" until the app is resumed.
The example just shows a "long task", but the truth is that most js code won't work in background even if it's inside the before exit, the only utility would be to make a plugin call so the native code will continue to work for that extended period, so it would do the upload from native.
